name: Static Code Analysis
on: [push, pull_request]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Static Analysis Tools
        run: sudo apt update && sudo apt install -y cppcheck clang-tidy

      - name: Run Analysis
        run: make static-analysis
